set nocompatible

filetype off

" Vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Plugins
Bundle 'gmarik/vundle'
Bundle 'tpope/vim-abolish'
Bundle 'tpope/vim-endwise'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-fugitive'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/syntastic'
Bundle 'vim-scripts/loremipsum'
Bundle 'vim-scripts/taglist.vim'
Bundle 'ervandew/supertab'
Bundle 'fholgado/minibufexpl.vim'
Bundle 'jcf/vim-latex'
Bundle 'kien/ctrlp.vim'
Bundle 'majutsushi/tagbar'
Bundle 'sjl/gundo.vim'
Bundle 'mattn/gits-vim'

filetype plugin indent on
" Read vim config file
if filereadable($HOME . "/.vim/config/settings.vim")
  source ~/.vim/config/settings.vim
endif
au BufRead *.c,*.h :silent %!indent -bli0 -npsl -i3 -ts0 -sob
