#!/bin/env bash


function cd()
{
  builtin cd "$*" && ls
}

function presley()
{
  if [ ! $TERM == "xterm" ]; then
    export TERM=xterm
  fi

  elvis $1
  export TERM=rxvt-256color
}

function mktlzo()
{
  if [ "$#" -ne 1 ]; then
    echo "usage: mktlzo <fichier ou répertoire>"
    return 1
  fi

  tar cvf "${1%%/}.tar" "${1%%/}/" && lzop -U -9 "${1%%/}.tar"
}


function noel()
{
  if [ "$#" -ne 1 ]; then
    echo "usage: noel <image>"
    return 1
  fi

  curl -F fichier="@$1" http://www.noelshack.com/api.php;
  printf "\n";
}

function passgen()
{
  LEN=${1:-16}

  if [ "$1" == "-h" ]; then
    echo "usage: passgen <length> <some additional chars>"
    return 1
  fi

  tr -dc A-Za-z0-9_$2 < /dev/urandom | head -c $LEN | xargs
}

function extract()
{
  if [ "$#" -ne 1 ]; then
    echo "usage: extract <archive>"
    return 1
  fi

  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1     ;;
      *.tar.gz)    tar xzf $1     ;;
      *.bz2)       bunzip2 $1     ;;
      *.rar)       unrar e $1     ;;
      *.gz)        gunzip $1      ;;
      *.tar)       tar xf $1      ;;
      *.tbz2)      tar xjf $1     ;;
      *.tgz)       tar xzf $1     ;;
      *.zip)       unzip $1       ;;
      *.Z)         uncompress $1  ;;
      *.7z)        7z x $1        ;;
      *)     echo "'$1' ne peut pas être extrait par cette fonction." ;;
    esac
  else
    echo "'$1' n'est pas un fichier valide."
  fi
}
